//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStoreRestApi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sales
    {
        public int id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<decimal> amount { get; set; }
    
        public virtual tbl_orders tbl_orders { get; set; }
    }
}
