//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStoreRestApi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_orders()
        {
            this.tbl_order_details = new HashSet<tbl_order_details>();
            this.tbl_sales = new HashSet<tbl_sales>();
        }
    
        public int id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<int> address_id { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public byte[] payment_status { get; set; }
    
        public virtual tbl_customer tbl_customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_order_details> tbl_order_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_sales> tbl_sales { get; set; }
        public virtual tbl_address tbl_address { get; set; }
    }
}
